---
# tasks file for ansible_chef_install
- name: install and configure chef dk
  block:
    - name: Setup default git configuraiton
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - {name: "user.name",  value: "{{ git_username }}" }
        - {name: "user.email", value: "{{ git_email }}" }
        - {name: "ui.color",   value: "True" }

    - name: install chef dk package
      yum:
        name: https://packages.chef.io/files/stable/chefdk/{{ chef_dk_version }}/el/{{ ansible_distribution_major_version }}/chefdk-{{ chef_dk_version }}-1.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm
        state: present

    - name: install ruby and dev
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - ruby
        - ruby-devel
        - make
        - cmake
        - gcc
        - git

    - name: install ruby dependencies
      gem:
        executable: /opt/chefdk/embedded/bin/gem
        install_dir: /root/.gem/ruby/bin
        user_install: no
        name: rugged
        version: 0.26.6
        state: present

    - name: verify chef
      shell: chef verify --chef-license=accept
      register: chef_verify
    - debug:
        msg: "{{ chef_verify.stdout }}"

    - name: add env PATH
      lineinfile:
        path: ~/.bash_profile
        line: export PATH="/opt/chefdk/embedded/bin:$PATH"

    - name: source env variable
      shell: source ~/.bash_profile
  tags:
    - chef_dk

- name: install and configure chef server
  block:
    - name: install dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - postgresql
        - iproute
        - ruby
        - ruby-devel
        - make
        - cmake
        - gcc
        - git

    - name: configure ruby repo  
      apt_repository:
        repo: 'ppa:brightbox/ruby-ng'

    - name: install ruby dependencies
      gem:
        executable: /usr/bin/gem
        install_dir: /root/.gem/ruby/bin
        user_install: no
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: present
      loop:
        - { name: ohai, version: 8.17.1 }

    - name: install chef server
      yum:
        name: https://packages.chef.io/files/stable/chef-server/{{ chef_server_version }}/el/{{ ansible_distribution_major_version }}/chef-server-core-{{ chef_server_version }}-1.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm
        state: present

    - name: configure chef server
      block:
        - name: configure chef dk
          shell: chef-server-ctl reconfigure --chef-license=accept

      rescue:
        - name: cleanse chef
          shell: chef-server-ctl cleanse

    - name: chef dk status
      shell: chef-server-ctl status
      register: chef_status
    - debug:
        msg: "{{ chef_status }}"

    - name: print admin user information
      debug:
        msg: "User information is: {{ item.USER_NAME }} {{ item.FIRST_NAME }} {{ item.LAST_NAME }} {{ item.EMAIL }} {{ item.PASSWORD }} {{ item.PATH }}/{{ item.FILE_NAME }}"
      loop: "{{ admin_user_information }}"

    - name: create admin user
      shell: chef-server-ctl user-create {{ item.USER_NAME }} {{ item.FIRST_NAME }} {{ item.LAST_NAME }} {{ item.EMAIL }} "{{ item.PASSWORD }}" -f {{ item.PATH }}/{{ item.FILE_NAME }}
      loop: "{{ admin_user_information }}"
      register: admin_user_creation
    - debug:
        msg: "{{ admin_user_creation.stdout }}"

    - name: create organization
      shell: chef-server-ctl org-create {{ item.SHORT_NAME }} "{{ item.FULL_ORGANIZATION_NAME }}" --association_user {{ item.USER_NAME }} --filename {{ item.SHORT_NAME }}-validator.pem
      loop: "{{ organization_information }}"
      register: organization_creation
    - debug:
        msg: "{{ organization_creation.stdout }}"
  tags:
    - chef_server
